name: stylish
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  vector_math: ^2.2.0
  leak_tracker: ^11.0.2
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  test_api: ^0.7.7
  vm_service: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
